<?php

/**
 * @file
 * Create an archive of all news as list grouped by Year and month
 *
 */

/**
 * Implements hook_menu()
 */
 function news_archive_menu() {
   $items = array();
 
   $items['admin/config/news-archive'] = array(
     'title' => 'News Aarchive',
     'description' => 'Configure News Archive module settings.',
     'access arguments' => array('administer site configuration'),
     'file' => 'modules/news_archive_admin.inc',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('news_archive_admin'),    
     'weight' => -10,
   );
   
   
   $items['admin/config/news-archive/settings'] = array(
     'title' => 'News Archive Settings',
     'access callback' => TRUE,
     'type' => MENU_DEFAULT_LOCAL_TASK,
     'weight' => -10,
   );
   
   return $items;
   
 }
 
 
/**
 * CREATE THE BLOCK
 * Implements hook_block_info()
 */
 function news_archive_block_info() {
   $blocks = array();
   $blocks['news_archive_block'] = array(
     'info' => t('News Archive'),
   );
   
   return $blocks;
   
 }
 
/**
 * Implements hook_block_view()
 */
 function news_archive_block_view( $delta = '' ) {
   
   switch ( $delta ) {
     case 'news_archive_block' :
       $block['content'] = array(
         'news_archive' => array(
           '#type' => 'markup',
           '#markup' => get_article_archive($delta),
           '#attached' => array(
           'css' => array(
             drupal_get_path('module', 'news_archive') . '/css/news_archive.css',
             ),
             'js' => array(
               drupal_get_path('module', 'news_archive') . '/js/news_archive.js',
               array('data' => array('news_archive' => array('news_archive_path' => "http://" . $_SERVER['HTTP_HOST'] . base_path() . drupal_get_path('module',  'news_archive') ), ), 'type' => 'setting')
             ),
           ),
           '#prefix' => "<div class='news-archive-wrapper'>",
           '#suffix' => "</div>",
         ),
       );
       
       return $block;
       break;
  }
 }

/**
 * CUSTOM FUNCTIONS
 */ 
 
 function get_article_archive( $delta ) {
   switch ( $delta ) {
     case 'news_archive_block' :

       $table = 'field_data_' . variable_get('news_archive_content_type_fields');
       $field = variable_get('news_archive_content_type_fields') . '_value';
   
       $current_post = _get_current_node_info( arg(count(arg()) -1 ), $field, $table );
       
       //_array_print( $current_post );
       
       if (empty( $current_post ) ) {
        $current_post = array('year' => date("Y"), 'month' => date("F"), 'nid' => NULL);
        //_array_print( $current_post );
       }

       $res_year = db_query('SELECT DISTINCT Year(' . $field . ') FROM {' . $table . '} ORDER BY Year(' . $field . ') DESC')->fetchCol();

       $res_months = array();
       
       
       $count = 0;
       
       //GET ALL FIELD OF A GIVEN BUNDLE
       //print 'SELECT field_name FROM field_config_instance WHERE bundle ="' . variable_get('news_archive_content_type') . '"';
       $fields = db_query("SELECT field_name FROM {field_config_instance} WHERE bundle ='" . variable_get('news_archive_content_type') . "'")->fetchCol();
       //_array_print($fields);

       $posts = array();

       $html = "<ul class='news-archive'>\n";
       
       $tester = array();
       
       $class_year = "";
       $class_month = "";
       $class_post = "";
       
       foreach ($res_year as $row) {
        
        ($row == $current_post['year']) ? $class_year = 'active' : $class_year = '';
        
        $html .= "<li class='news-archive-year-leaf year-" . $row . " " . $class_year . "'>\n";
        $html .= $row . "\n";
        $html .= "\t<ul class='news-archive-month'>\n";
        
         //print 'SELECT Month(' . $field . '), entity_id FROM ' . $table . ' WHERE Year(' . $field . ') = ' . $row .' ORDER BY Year(' . $field . ') DESC' . '<br>';
        $months = db_query('SELECT DISTINCT Monthname(' . $field . ') FROM {' . $table . '} WHERE Year(' . $field . ') = ' . $row . ' ORDER BY Year(' . $field . ') DESC')->fetchCol();
        
        $count_months = 0;
        
        foreach ($months as $row_m => $val_m) {
          
          ($val_m == $current_post['month'] && $row == $current_post['year'] ) ? $class_month = 'active' : $class_month = '';

          $rows = db_query("SELECT entity_id FROM {" . $table . "} WHERE Year(" . $field . ") = " . $row . " AND Monthname(" . $field . ") ='" . $val_m . "' ORDER BY Year(" . $field . ") DESC, Month(" . $field . ") DESC")->fetchCol();
          
          //GET ARTICLE COUNT
          $rows_count = 0;
          foreach ( $rows as $nid ) {
            
            ($nid == $current_post['nid']) ? $class_post = 'active' : $class_post = '';

            $rows_count = db_query("SELECT title FROM {node} WHERE nid = " . $nid )->rowCount();

          }


          $html .= "\t\t<li class='news-archive-month-leaf month-" . strtolower(t($val_m)) . " " . $class_month . "'>\n";
          $html .= "\t\t\t" . t($val_m) . " (" . $rows_count . ")\n";
          //print "SELECT entity_id FROM {" . $table . "} WHERE Monthname(" . $field . ") ='" . $val_m . "' AND Year(" . $field . ") = " . $row . " ORDER BY Year(" . $field . ") DESC<br>";
         
          
          $html .= "\t\t\t\t<ul class='news-archive-posts'>";
          
          $level_2 = array();
          $str_builder = "";
          
          foreach ( $rows as $nid ) {
            
           ($nid == $current_post['nid']) ? $class_post = 'active' : $class_post = '';

           $title = db_query("SELECT title FROM {node} WHERE nid = " . $nid )->fetchCol();

           $node = node_load($nid);
           $path = drupal_lookup_path('alias', 'node/' . $node->nid);

           $link = l( $title[0], "http://" . $_SERVER['HTTP_HOST'] . base_path() . $path);

           $html .= "<li class='news-archive-posts-leaf post-" . $node->nid . " " . $class_post . "'>" . $link . "</li>";

         }
       
          $html .= "\t\t\t\t</ul>";
          
          $html .="\t\t</li>";
          
          $count_months++;
          
        }
        
        $level_1 = array();
        
        $res_months[$count] = array( $row => $posts);
        
        $posts = array();
       
        $html .= "\t</ul>";
        $html .= "</li>";
        
        $count++;
       }
       
       $html .= "</ul>";
       
       return $html;
       
       break;
   }
 }
 
 
 function _get_current_node_info( $nid, $field, $table ) {
   
   $info = array();
   
   $nid_year = db_query('SELECT DISTINCT Year(' . $field . ') FROM {' . $table . '} WHERE entity_id = ' . $nid . ' ORDER BY Year(' . $field . ') DESC')->fetchColumn(0);
   $nid_month = db_query('SELECT DISTINCT Monthname(' . $field . ') FROM {' . $table . '} WHERE entity_id = ' . $nid . ' ORDER BY Year(' . $field . ') DESC')->fetchColumn(0);
   
   if ( $nid_year == "" || $nid_month == "" ) {
     return array();
   }
   else {   
     return array('year' => $nid_year, 'month' => $nid_month, 'nid' => $nid);
   }
 }
 
 function _array_print( $ar = array() ) {
  
   print '<pre>';
   print_r( $ar );
   print '</pre><hr />';
   
 }